services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - http.host=0.0.0.0
    ports:
      - 9201:9201
    volumes:
      - esdata:/usr/share/elasticsearch/data
    # healthcheck:
    #     test: ["CMD", "curl", "-f", "http://localhost:9201"]
    #     interval: 30s
    #     timeout: 10s
    #     retries: 5
  flask:
    image: flask
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9200
    restart: on-failure
    depends_on:
      - elasticsearch
    ports:
      - 5002:5002

volumes:
  esdata:
